version: "3"
services:
 
  mysql_master:
    image: crysiscore/mysql_master:v5.6
    volumes:
      - /home/agnaldo/Documents/openmrs/backups:/data
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: esaude 
        MYSQL_DATABASE: openmrs
        MYSQL_PASSWORD: esaude
    ports:
      - "3310:3306"   
    networks:
      my-overlay:
          ipv4_address: "10.0.3.2"

    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  mysql_slave:
    image: crysiscore/mysql_slave:v5.6
    volumes:
      - /home/agnaldo/Documents/openmrs/backups:/data
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: esaude 
        MYSQL_DATABASE: openmrs
        MYSQL_PASSWORD: esaude
        MYSQL_MASTER_SERVICE_HOST: "10.0.3.2"
        MYSQL_REPLICATION_USER: slave 
        MYSQL_REPLICATION_PASSWORD: password

    networks:
      - my-overlay

    ports:
     - "3312:3306"  
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]

networks:
  my-overlay:
 